apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eap0ars7h-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/eap0ars7h-java-quarkus-gitops